- name: demo on task level variables
  hosts: localhost 
  connection: local # it will not asl for user name and password
  vars:
    COURSE: "Ansible"
    TRAINER: "Gopi"
    DURATION: "150 HRS"
  task: 
  - name: print "DevOps with AIOps"
  vars:
    COURSE: "DevsecOps with AIOps"
  debug:
   msg: "Hi, I am  Learning {{COURSE}}, Trainer is {{ TRAINER }}, Duration is {{ Duration}}"
   
